/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sekiguchikai' at '16/11/11 20:09' with Gradle 3.1
 *
 * @author sekiguchikai, @date 16/11/11 20:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
